name: green_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  provider: ^6.1.5+1

  # --- UI ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # --- State Management ---
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # --- Dependency Injection ---
  get_it: ^7.7.0
  injectable: ^2.4.2

  # --- Stream Transform ---
  stream_transform: ^2.1.0

  # --- Functional Programming & Utils ---
  rxdart: ^0.27.7

  # --- Networking & Data ---
  dio: ^5.9.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  fpdart: ^1.2.0
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0

  # --- Multimedia & Files ---
  image_picker: ^1.0.4
  path_provider: ^2.1.0
  path: ^1.8.3
  file_selector: ^0.9.3+1 
  
  # --- IA ---
  google_generative_ai: ^0.4.7 

  # --- Utils & Scanner ---
  mobile_scanner: ^7.1.4
  socket_io_client: ^3.1.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # --- Code Generation ---
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

  # --- BDD & Testing Tools (Basado en enfoque Cucumber/Cypress) ---
  # Mockito es el estÃ¡ndar para BDD en Flutter [cite: 10, 11]
  mockito: ^5.4.4
  # bdd_widget_test permite pasar de User Stories a Especificaciones Ejecutables [cite: 17, 63]
  bdd_widget_test: ^1.6.0
  # flutter_gherkin es el equivalente a Cucumber para Flutter [cite: 98, 104]
  flutter_gherkin: ^2.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/appIcon.png
    - assets/purpleicon2.png